[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

# A basic redirects rule
[[redirects]]
  from = "/denver"
  to = "/denver-web-developer"

